name: CI/CD Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT }}
      REGION: us-central1
      ARTIFACT_REPO: inovarepo
      PORT: 4000
    steps:
      # Checkout the repo
      - uses: actions/checkout@v4

      # Write service account key to a file
      - name: Set up GCP credentials
        run: |
          mkdir -p $HOME
          echo '${{ secrets.GCP_SA_KEY }}' > ${{ github.workspace }}/gcp-key.json

      # Configure Docker to push to Artifact Registry
      - name: Configure docker for Artifact Registry
        run: |
          gcloud auth activate-service-account --key-file=${{ github.workspace }}/gcp-key.json
          gcloud --quiet auth configure-docker ${REGION}-docker.pkg.dev

      # Build & push API Docker image with PORT argument
      - name: Build & push API image
        run: |
          docker build --build-arg PORT=${PORT} \
            -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${ARTIFACT_REPO}/inova-api:${{ github.sha }} ./api
          docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${ARTIFACT_REPO}/inova-api:${{ github.sha }}

      # Replace image tag in Terraform variables
      - name: Replace image tag in Terraform (local var)
        run: |
          echo "image_tag = \"${REGION}-docker.pkg.dev/${PROJECT_ID}/${ARTIFACT_REPO}/inova-api:${{ github.sha }}\"" > infra/terraform.tfvars

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Terraform Init
      - name: Terraform Init
        working-directory: infra
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json
        run: terraform init

      # Terraform Apply
      - name: Terraform Apply
        working-directory: infra
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json
        run: terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT }}" -var="region=us-central1" -var="db_password=${{ secrets.DB_PASSWORD }}" -var="db_instance_name=inovadb-instance" -var="artifact_repo=inovarepo" -var="webhook_api_key=${{ secrets.WEBHOOK_API_KEY }}" -var="image_tag=${{ github.sha }}"

